
# Required due to VirtualBox Guest Addition probles caused by
# different Versions of VirtualBox
unless Vagrant.has_plugin?("vagrant-vbguest")
    raise Vagrant::Errors::VagrantError.new, "Plugin missing: vagrant-vbguest - please install via vagrant plugin install"
end

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "2024"]
  end

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8080
  #config.vm.network :hostonly, "33.33.33.10"
  
  config.vm.synced_folder "/Desktop/Debian VMware/Wien-Wahl/csv_tools", "/home/vagrant/CSV-Tools"
  config.vm.synced_folder "~/.virtualenvs", "/home/vagrant/.virtualenvs"

  # Install project dependicies
  config.vm.provision :shell, :path => "./install.sh"
end
